//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TU_Grafik.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonus
    {
        public int BonusId { get; set; }
        public string type { get; set; }
        public Nullable<int> BonusHallRef { get; set; }
    
        public virtual Hall Hall { get; set; }


    }
}
