//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TU_Grafik.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hall
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hall()
        {
            this.Bonuses = new HashSet<Bonus>();
        }
    
        public int HallID { get; set; }
        public string type { get; set; }
        public string nummber { get; set; }
        public byte[] beginningOfLesson { get; set; }
        public Nullable<System.DateTime> endOfLesson { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bonus> Bonuses { get; set; }
        public virtual HallGroup HallGroup { get; set; }
        public virtual HallSchedule HallSchedule { get; set; }
        public virtual HallSubject HallSubject { get; set; }
    }
}
