//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TU_Grafik.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public string TeacheID { get; set; }
        public string name { get; set; }
        public byte[] begginingOfLesson { get; set; }
        public Nullable<System.DateTime> endOfLesson { get; set; }
        public string comment { get; set; }
    
        public virtual HallSchedule HallSchedule { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
